/**
 * Social-card asset references and dimensions.
 *
 * Cards are generated by `scripts/media/generate-social-cards.ts` from the
 * portfolio's own typography and media; this module is the single source of
 * the card contract shared by the generator and the SEO component.
 */

export const SOCIAL_CARD_WIDTH = 1200;
export const SOCIAL_CARD_HEIGHT = 630;

export interface SocialCardSpec {
  /** Site-relative public path, e.g. `/social/home.png`. */
  path: string;
  /** Human-readable title used both as file alt and OG fallback. */
  label: string;
}

export const defaultSocialCard: SocialCardSpec = Object.freeze({
  path: '/social/home.png',
  label: 'lxrdxe7o — Full-Stack Developer',
});

export const socialCards: Readonly<Record<string, SocialCardSpec>> =
  Object.freeze({
    home: defaultSocialCard,
    projects: Object.freeze({ path: '/social/projects.png', label: 'Work — lxrdxe7o' }),
    about: Object.freeze({ path: '/social/about.png', label: 'About — Ishraful Haque' }),
    writing: Object.freeze({ path: '/social/writing.png', label: 'Writing — lxrdxe7o' }),
    notes: Object.freeze({ path: '/social/notes.png', label: 'Notes — lxrdxe7o' }),
    lab: Object.freeze({ path: '/social/lab.png', label: 'Lab — lxrdxe7o' }),
    contact: Object.freeze({ path: '/social/contact.png', label: 'Contact — lxrdxe7o' }),
  });

export function socialCardForRoute(routeId: string): SocialCardSpec {
  return socialCards[routeId] ?? defaultSocialCard;
}
