// Generated by scripts/media/build-manifest.ts. Do not edit by hand.
import type { MediaManifest } from '../../types/media';

export const xeroDevMediaManifest: MediaManifest = {
  "schemaVersion": 1,
  "projectSlug": "xero-dev",
  "generatedAt": "2026-07-31T14:08:37.780Z",
  "assets": [
    {
      "id": "xero-dev-desktop-hero",
      "kind": "image",
      "projectSlug": "xero-dev",
      "sourceProvenance": "https://lxrdxe7o.vercel.app/ @ 2026-07-31T14:08:37.780Z (seed 1, Desktop — Landing hero)",
      "alt": "xero-dev — Desktop view, landing hero",
      "reducedDataEligible": true,
      "preload": "high",
      "aspectRatio": 1.6,
      "variants": [
        {
          "format": "avif",
          "width": 640,
          "height": 400,
          "bytes": 13062,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-640.avif"
        },
        {
          "format": "jpeg",
          "width": 640,
          "height": 400,
          "bytes": 24370,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-640.jpeg"
        },
        {
          "format": "webp",
          "width": 640,
          "height": 400,
          "bytes": 14718,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-640.webp"
        },
        {
          "format": "avif",
          "width": 960,
          "height": 600,
          "bytes": 23167,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-960.avif"
        },
        {
          "format": "jpeg",
          "width": 960,
          "height": 600,
          "bytes": 52522,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-960.jpeg"
        },
        {
          "format": "webp",
          "width": 960,
          "height": 600,
          "bytes": 26918,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-960.webp"
        },
        {
          "format": "avif",
          "width": 1280,
          "height": 800,
          "bytes": 34820,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-1280.avif"
        },
        {
          "format": "jpeg",
          "width": 1280,
          "height": 800,
          "bytes": 81290,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-1280.jpeg"
        },
        {
          "format": "webp",
          "width": 1280,
          "height": 800,
          "bytes": 39388,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-1280.webp"
        },
        {
          "format": "avif",
          "width": 1920,
          "height": 1200,
          "bytes": 56067,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-1920.avif"
        },
        {
          "format": "jpeg",
          "width": 1920,
          "height": 1200,
          "bytes": 147610,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-1920.jpeg"
        },
        {
          "format": "webp",
          "width": 1920,
          "height": 1200,
          "bytes": 66024,
          "path": "/media/projects/xero-dev/xero-dev-desktop-hero-1920.webp"
        }
      ]
    },
    {
      "id": "xero-dev-desktop-loop",
      "kind": "video",
      "projectSlug": "xero-dev",
      "sourceProvenance": "https://lxrdxe7o.vercel.app/ @ 2026-07-31T14:08:37.780Z (seed 1, 6000ms loop)",
      "alt": "xero-dev — muted interface loop",
      "posterAssetId": "xero-dev-desktop-loop-poster",
      "reducedDataEligible": false,
      "preload": "none",
      "aspectRatio": 1.6,
      "variants": [
        {
          "format": "mp4",
          "width": 1440,
          "height": 900,
          "bytes": 1391567,
          "path": "/media/projects/xero-dev/xero-dev-desktop-loop.mp4"
        },
        {
          "format": "webm",
          "width": 1440,
          "height": 900,
          "bytes": 761162,
          "path": "/media/projects/xero-dev/xero-dev-desktop-loop.webm"
        }
      ]
    },
    {
      "id": "xero-dev-desktop-loop-poster",
      "kind": "image",
      "projectSlug": "xero-dev",
      "sourceProvenance": "https://lxrdxe7o.vercel.app/ @ 2026-07-31T14:08:37.780Z (seed 1, video poster frame)",
      "alt": "xero-dev — interface loop poster frame",
      "reducedDataEligible": true,
      "preload": "none",
      "aspectRatio": 1.6,
      "variants": [
        {
          "format": "jpeg",
          "width": 1440,
          "height": 900,
          "bytes": 85496,
          "path": "/media/projects/xero-dev/xero-dev-desktop-loop-poster.jpg"
        }
      ]
    },
    {
      "id": "xero-dev-desktop-scroll-mid",
      "kind": "image",
      "projectSlug": "xero-dev",
      "sourceProvenance": "https://lxrdxe7o.vercel.app/ @ 2026-07-31T14:08:37.780Z (seed 1, Desktop — Mid-scroll composition)",
      "alt": "xero-dev — Desktop view, mid-scroll composition",
      "reducedDataEligible": false,
      "preload": "none",
      "aspectRatio": 1.6,
      "variants": [
        {
          "format": "avif",
          "width": 640,
          "height": 400,
          "bytes": 13120,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-640.avif"
        },
        {
          "format": "jpeg",
          "width": 640,
          "height": 400,
          "bytes": 24382,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-640.jpeg"
        },
        {
          "format": "webp",
          "width": 640,
          "height": 400,
          "bytes": 14660,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-640.webp"
        },
        {
          "format": "avif",
          "width": 960,
          "height": 600,
          "bytes": 23105,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-960.avif"
        },
        {
          "format": "jpeg",
          "width": 960,
          "height": 600,
          "bytes": 52556,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-960.jpeg"
        },
        {
          "format": "webp",
          "width": 960,
          "height": 600,
          "bytes": 27000,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-960.webp"
        },
        {
          "format": "avif",
          "width": 1280,
          "height": 800,
          "bytes": 34557,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-1280.avif"
        },
        {
          "format": "jpeg",
          "width": 1280,
          "height": 800,
          "bytes": 81317,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-1280.jpeg"
        },
        {
          "format": "webp",
          "width": 1280,
          "height": 800,
          "bytes": 39484,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-1280.webp"
        },
        {
          "format": "avif",
          "width": 1920,
          "height": 1200,
          "bytes": 55812,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-1920.avif"
        },
        {
          "format": "jpeg",
          "width": 1920,
          "height": 1200,
          "bytes": 147864,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-1920.jpeg"
        },
        {
          "format": "webp",
          "width": 1920,
          "height": 1200,
          "bytes": 66194,
          "path": "/media/projects/xero-dev/xero-dev-desktop-scroll-mid-1920.webp"
        }
      ]
    },
    {
      "id": "xero-dev-mobile-hero",
      "kind": "image",
      "projectSlug": "xero-dev",
      "sourceProvenance": "https://lxrdxe7o.vercel.app/ @ 2026-07-31T14:08:37.780Z (seed 1, Mobile — Landing hero)",
      "alt": "xero-dev — Mobile view, landing hero",
      "reducedDataEligible": true,
      "preload": "none",
      "aspectRatio": 0.46208530805687204,
      "variants": [
        {
          "format": "avif",
          "width": 640,
          "height": 1385,
          "bytes": 32854,
          "path": "/media/projects/xero-dev/xero-dev-mobile-hero-640.avif"
        },
        {
          "format": "jpeg",
          "width": 640,
          "height": 1385,
          "bytes": 76593,
          "path": "/media/projects/xero-dev/xero-dev-mobile-hero-640.jpeg"
        },
        {
          "format": "webp",
          "width": 640,
          "height": 1385,
          "bytes": 39234,
          "path": "/media/projects/xero-dev/xero-dev-mobile-hero-640.webp"
        },
        {
          "format": "avif",
          "width": 960,
          "height": 2078,
          "bytes": 49126,
          "path": "/media/projects/xero-dev/xero-dev-mobile-hero-960.avif"
        },
        {
          "format": "jpeg",
          "width": 960,
          "height": 2078,
          "bytes": 131477,
          "path": "/media/projects/xero-dev/xero-dev-mobile-hero-960.jpeg"
        },
        {
          "format": "webp",
          "width": 960,
          "height": 2078,
          "bytes": 60928,
          "path": "/media/projects/xero-dev/xero-dev-mobile-hero-960.webp"
        }
      ]
    },
    {
      "id": "xero-dev-mobile-scroll-mid",
      "kind": "image",
      "projectSlug": "xero-dev",
      "sourceProvenance": "https://lxrdxe7o.vercel.app/ @ 2026-07-31T14:08:37.780Z (seed 1, Mobile — Mid-scroll composition)",
      "alt": "xero-dev — Mobile view, mid-scroll composition",
      "reducedDataEligible": false,
      "preload": "none",
      "aspectRatio": 0.46208530805687204,
      "variants": [
        {
          "format": "avif",
          "width": 640,
          "height": 1385,
          "bytes": 33227,
          "path": "/media/projects/xero-dev/xero-dev-mobile-scroll-mid-640.avif"
        },
        {
          "format": "jpeg",
          "width": 640,
          "height": 1385,
          "bytes": 77479,
          "path": "/media/projects/xero-dev/xero-dev-mobile-scroll-mid-640.jpeg"
        },
        {
          "format": "webp",
          "width": 640,
          "height": 1385,
          "bytes": 39934,
          "path": "/media/projects/xero-dev/xero-dev-mobile-scroll-mid-640.webp"
        },
        {
          "format": "avif",
          "width": 960,
          "height": 2078,
          "bytes": 49997,
          "path": "/media/projects/xero-dev/xero-dev-mobile-scroll-mid-960.avif"
        },
        {
          "format": "jpeg",
          "width": 960,
          "height": 2078,
          "bytes": 133338,
          "path": "/media/projects/xero-dev/xero-dev-mobile-scroll-mid-960.jpeg"
        },
        {
          "format": "webp",
          "width": 960,
          "height": 2078,
          "bytes": 62198,
          "path": "/media/projects/xero-dev/xero-dev-mobile-scroll-mid-960.webp"
        }
      ]
    }
  ]
};
