import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type {
  MediaAssetDescriptor,
  MediaAssetVariant,
  MediaManifest,
} from '../../src/types/media.ts';
import { MAX_VIDEO_VARIANT_BYTES } from './encode-video.ts';
import { MAX_IMAGE_VARIANT_BYTES } from './process-images.ts';

const IMAGE_FORMAT_SET = new Set<MediaAssetVariant['format']>(['avif', 'webp', 'jpeg']);

function budgetFor(format: MediaAssetVariant['format']): number {
  return IMAGE_FORMAT_SET.has(format) ? MAX_IMAGE_VARIANT_BYTES : MAX_VIDEO_VARIANT_BYTES;
}

export interface BuildManifestOptions {
  projectSlug: string;
  assets: MediaAssetDescriptor[];
  generatedAt?: string;
}

/**
 * Validates the constraints a manifest must hold before it may ship:
 * unique asset ids, alt text on every non-decorative image and every video,
 * a resolvable poster for every video, and at least one encoded variant per
 * asset. Throws with an actionable message on the first violation rather
 * than silently dropping an asset.
 */
export function validateManifestAssets(assets: readonly MediaAssetDescriptor[]): void {
  const idsSeen = new Set<string>();

  for (const asset of assets) {
    if (idsSeen.has(asset.id)) {
      throw new Error(`Duplicate media asset id: "${asset.id}"`);
    }
    idsSeen.add(asset.id);

    if (asset.kind === 'image' && !asset.decorative && !asset.alt) {
      throw new Error(`Image asset "${asset.id}" requires alt text unless marked decorative.`);
    }
    if (asset.kind === 'video' && !asset.alt) {
      throw new Error(`Video asset "${asset.id}" requires an accessible description.`);
    }
    if (asset.kind === 'video' && !asset.posterAssetId) {
      throw new Error(`Video asset "${asset.id}" requires a linked poster asset (posterAssetId).`);
    }
    if (asset.variants.length === 0) {
      throw new Error(`Asset "${asset.id}" has no encoded variants.`);
    }
    if (!asset.sourceProvenance) {
      throw new Error(`Asset "${asset.id}" is missing source provenance.`);
    }
    for (const variant of asset.variants) {
      const budget = budgetFor(variant.format);
      if (variant.bytes > budget) {
        throw new Error(
          `Asset "${asset.id}" variant "${variant.path}" is ${variant.bytes} bytes, exceeding the ${budget}-byte budget for "${variant.format}".`,
        );
      }
    }
  }

  for (const asset of assets) {
    if (asset.posterAssetId && !idsSeen.has(asset.posterAssetId)) {
      throw new Error(
        `Video asset "${asset.id}" references missing poster asset "${asset.posterAssetId}".`,
      );
    }
  }
}

function sortVariants(variants: readonly MediaAssetVariant[]): MediaAssetVariant[] {
  return [...variants].sort((a, b) => a.width - b.width || a.format.localeCompare(b.format));
}

/**
 * Builds a validated, deterministic {@link MediaManifest} from processed
 * asset descriptors. Variant ordering is normalized (ascending width, then
 * format) so two builds from the same input produce byte-identical JSON.
 */
export function buildMediaManifest(options: BuildManifestOptions): MediaManifest {
  validateManifestAssets(options.assets);

  const assets = [...options.assets]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((asset) => ({ ...asset, variants: sortVariants(asset.variants) }));

  return {
    schemaVersion: 1,
    projectSlug: options.projectSlug,
    generatedAt: options.generatedAt ?? new Date().toISOString(),
    assets,
  };
}

export interface ResponsiveSourceSelection {
  srcset: string;
  /** A conservative default `sizes` hint; routes may override per layout. */
  sizesHint: string;
  fallback: MediaAssetVariant;
}

/**
 * Selects every variant of one format for an asset and returns a ready-to-use
 * `srcset` string plus a fallback (the largest variant), so a route/component
 * can render responsive sources without re-deriving candidate ordering.
 */
export function selectResponsiveSources(
  asset: MediaAssetDescriptor,
  format: MediaAssetVariant['format'],
): ResponsiveSourceSelection {
  const candidates = asset.variants
    .filter((variant) => variant.format === format)
    .sort((a, b) => a.width - b.width);

  if (candidates.length === 0) {
    throw new Error(`Asset "${asset.id}" has no "${format}" variants.`);
  }

  return {
    srcset: candidates.map((variant) => `${variant.path} ${variant.width}w`).join(', '),
    sizesHint: '(min-width: 1024px) 100vw, 100vw',
    fallback: candidates[candidates.length - 1],
  };
}

/** Renders a manifest as a typed, importable TypeScript module. */
export function renderManifestModule(manifest: MediaManifest): string {
  return `// Generated by scripts/media/build-manifest.ts. Do not edit by hand.
import type { MediaManifest } from '../../types/media';

export const ${toModuleIdentifier(manifest.projectSlug)}MediaManifest: MediaManifest = ${JSON.stringify(manifest, null, 2)};
`;
}

function toModuleIdentifier(slug: string): string {
  return slug.replace(/-([a-z0-9])/gi, (_, char: string) => char.toUpperCase());
}

/** Writes a manifest to `src/data/media-manifests/<slug>.ts` as a typed module. */
export async function writeManifestModule(manifest: MediaManifest, outputPath: string): Promise<void> {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderManifestModule(manifest), 'utf8');
}
